### ISSUE TITLE
Port to Wahoo?

### ISSUE THREAD

**Issue by ghost** [hanny24/functional#1]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a decent Wahoo plugin or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards.

**Comment by hanny24** [comment]
Look's quite good! Is there anything special that needs to be done in order to become Wahoo plugin. After a quick look, it seems to me I can use this repository as is it now...

**Comment by ghost** [comment]
@hanny24 Hi! I deprecated Wahoo a long time ago, and now I am working on a new system, Fisherman.

I have already added `functional` to the index. Please let me know if you plan to maintain this repo.

Great work!

**Comment by hanny24** [comment]
Yes, this repo is still alive...and hopefully it will be in the future.

**Comment by ghost** [comment]
Wonderful. Thanks.
